AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 150

Metrics/ClassLength:
  Max: 1000

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Metrics/ParameterLists:
  Max: 10

Style/DoubleNegation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SignalException:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Next:
  Enabled: false

Style/ClassVars:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/ToJSON:
  Enabled: false

Lint/LiteralInInterpolation:
  Enabled: false
