##
# Used to test Salus is operating correctly in the docker container itself.
##
# docker build -t salus-local .
# docker build -f Dockerfile.tests -t salus-tests .
# docker run salus-tests

FROM salus-local

RUN apt-get update && apt-get upgrade -y --no-install-recommends && apt-get install -y --no-install-recommends \
  make gcc

COPY Gemfile Gemfile.lock ./

RUN bundle install --with test

COPY spec /home/spec

ENTRYPOINT ["bundle", "exec", "rspec", "--format", "documentation", "spec/"]
