version: 2
jobs:
  build:
   machine: true
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: rvm uninstall 2.3.1
      - run: rvm use 2.4.4
      - run: gem install bundler
      - run: bundle install
      - run: bundle-audit update
      - run: npm install -g npm
      - run: npm install
      - run: go get github.com/svent/sift
      - run: bundle exec rspec --format documentation
  salus:
    machine: true
    steps:
      - checkout
      - run: docker run -v $(pwd):/home/repo coinbase/salus
  rubocop:
    docker:
      - image: ruby:2.4.4@sha256:99d10d192ac1df0873480b1e0262ff0295a15f1d97e5b7bd111a7bf61a808acc
    steps:
      - run: apt-get update
      - run: apt-get install -y cmake
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop
workflows:
  version: 2
  build_and_lint:
    jobs:
      - build
      - rubocop
