version: 2
jobs:
  tests:
    machine: true
    steps:
      - checkout
      - run: docker build -t salus-local .
      - run: docker build -f Dockerfile.tests -t salus-tests .
      - run: docker run salus-tests
      - run: bin/integration_test
  salus:
    machine: true
    steps:
      - checkout
      - run: docker run -t -v $(pwd):/home/repo coinbase/salus
  rubocop:
    docker:
      - image: ruby:2.4.6@sha256:3a31984805c5ad3b54baeb93d2c01c46845f681b712394b02d2e860cb5d5946b
    steps:
      - checkout
      - run: apt-get update && apt-get install cmake -y
      - run: gem install bundler -v'2.0.2'
      - run: bundle install
      - run: bundle exec rubocop

workflows:
  version: 2
  build:
    jobs:
      - tests
      - rubocop
      - salus
