name: salus

on: push

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      actions: none
      checks: none
      contents: read
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none

    name: Build, and Push Salus Image
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SECURITY_PUBLISHER_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SECURITY_PUBLISHER_DOCKERHUB_PASSWORD }}

      - name: Build and Push container 1.16.9
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            bisontrails/salus:${{ github.sha }}
            bisontrails/salus:golang-1.16
          build-args: GO_VERSION=1.16.9,GO_SHA256=d2c095c95f63c2a3ef961000e0ecb9d81d5c68b6ece176e2a8a2db82dc02931c

      - name: Build and Push container 1.15.11
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            bisontrails/salus:${{ github.sha }}
            bisontrails/salus:golang-1.15
          build-args: GO_VERSION=1.15.11,GO_SHA256=8825b72d74b14e82b54ba3697813772eb94add3abf70f021b6bdebe193ed01ec

