---
on:
  - push
jobs:
  tests_job:
    runs-on: ubuntu-latest
    name: Salus Security Scan Example
    steps:
      - name: Build Salus
        run: docker build -t salus-local .
      - name: Build Tests
        run: docker build -f Dockerfile.tests -t salus-tests .
      - name: Run tests
        run: docker run salus-tests
      - name: Run integration
        run: bin/integration_test
